class AppStr:
    NO_IMAGE_DETECT = 'Lỗi: không lấy được ảnh'
    DETECT_SUCCESS = 'Nhận diện thành công'
    DETECT_FAILED = 'Nhận diện không thành công'
    PLEASE_WAIT = 'Xin vui lòng chờ giây lát'
    CANT_READ_SCALE = 'Không đọc được giá trị cân'
    ERROR_SAVE_INFO = 'Lỗi trong quá trình lưu'
    ERROR_FIELD_CONTENTS = 'Các trường thông tin không hợp lệ'
    ERROR = 'Có lỗi xảy ra'
    CONTINUE = 'Tiếp tục'
    CANCEL = 'Hủy bỏ'
    CAM_ERROR = 'Loi ket noi camera, vui long kiem tra lai ket noi mang, camera hoac lien he bo phan ho tro'
    SCALE_ERROR = 'Loi ket noi voi can, vui long kiem tra day cam va can hoac lien he nguoi ho tro'
    CAM_ERROR_TITLE = 'Loi ket noi camera'
    SCALE_ERROR_TITLE = 'loi ket noi can'